# Generated by Django 2.1.7 on 2019-04-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='target_language',
            field=models.CharField(default='en', max_length=5),
            preserve_default=False,
        ),
    ]
