# Generated by Django 2.1.7 on 2019-04-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_translation_target_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='source_language',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
